<Query Kind="Program" />

void Main()
{
	string[] originalLinks =
	{
        "[Karma](https://karma-runner.github.io/1.0/index.html)",
        "[MDN - Strict mode](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode)",
        "[MDN - Function](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function)",
        "[MDN - Arguments Object](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/arguments)",
        "[JavaScript Objects and Prototypes (by Jim Cooper)](https://app.pluralsight.com/library/courses/javascript-objects-prototypes/table-of-contents)",
        "[Stop Nesting Functions! (But Not All of Them)](https://code.tutsplus.com/tutorials/stop-nesting-functions-but-not-all-of-them--net-22315)",
        "[Object.defineProperty()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperties)",
        "[MDN Object](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object)",
        "[call()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/call)",
        "[apply()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/apply)",
        "[bind()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/bind)",
        "[w3schools link](http://www.w3schools.com/jsref/jsref_obj_string.asp)",
        "[MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String)",
        "[w3schools](http://www.w3schools.com/js/js_numbers.asp)",
        "[Number](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number)",
        "[MDN - Array](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array)",
        "[w3schools - Array](http://www.w3schools.com/jsref/jsref_obj_array.asp)",
        "[lodash](https://lodash.com/)",
        "[lazy.js](http://danieltao.com/lazy.js/)",
        "[w3schools - JavaScriptDate Reference](http://www.w3schools.com/jsref/jsref_obj_date.asp)",
        "[w3schools - JavaScript Date Formats](http://www.w3schools.com/js/js_date_formats.asp)",
        "[MDN - Date](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Date)",
        "[moment.js](http://momentjs.com/)",
        "[Regular-Expressions.info](http://www.regular-expressions.info/)",
        "[regex101.com](https://regex101.com/)",
        "[RegExp](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/RegExp)",
        "[MDN - Object](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object)",
        "[https://developer.mozilla.org/en/docs/Web/JavaScript/Inheritance_and_the_prototype_chain](https://developer.mozilla.org/en/docs/Web/JavaScript/Inheritance_and_the_prototype_chain)",
        "[MDN - Object.create()](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Object/create)",
        "[MDN - Function.prototype.bind()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/bind)",
        "[arguments object](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/arguments)",
        "[http://www.w3schools.com/js/js_reserved.asp](http://www.w3schools.com/js/js_reserved.asp)",
        "[Comparison Operators & Equality](#language-comparison-operators)",
        "[https://www.sitepoint.com/javascript-truthy-falsy/](https://www.sitepoint.com/javascript-truthy-falsy/)",
        "[MDN - Operator Precedence](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Operators/Operator_Precedence)",
        "[w3schools - Comparison and Logical Operators](http://www.w3schools.com/js/js_comparisons.asp)",
        "[MDN - typeof](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/typeof)",
        "[MDN - instanceof](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/instanceof)",
        "[w3schools - The Window Object](http://www.w3schools.com/jsref/obj_window.asp)",
        "[MDN - Window](https://developer.mozilla.org/en-US/docs/Web/API/Window)",
        "[Location object](http://www.w3schools.com/jsref/obj_location.asp)",
        "[jQuery](https://jquery.com/)",
        "[MDN - Document](https://developer.mozilla.org/en/docs/Web/API/Document)",
        "[w3schools - Math Reference](http://www.w3schools.com/jsref/jsref_obj_math.asp)",
        "[MDN - Math](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math)",
        "[http://www.jsonlint.com/](http://www.jsonlint.com/)",
        "[w3schools - JavaScript JSON](http://www.w3schools.com/js/js_json.asp)",
        "[MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse)",
        "[MDN - Console](https://developer.mozilla.org/en/docs/Web/API/console)",
        "[Beyond Console Debugging Tricks](https://medium.com/outsystems-experts/beyond-console-debugging-tricks-f7d0d7f5df4#.pmwwd5e9g)",
        "[JavaScript Global Reference](http://www.w3schools.com/jsref/jsref_obj_global.asp)",
        "[w3schools - JavaScript Best Practices](http://www.w3schools.com/js/js_best_practices.asp)",
        "[https://code.tutsplus.com/tutorials/stop-nesting-functions-but-not-all-of-them--net-22315](https://code.tutsplus.com/tutorials/stop-nesting-functions-but-not-all-of-them--net-22315)",
        "[MDN - Defining getters and setters](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Working_with_Objects#Defining_getters_and_setters)",
        "[React’s JSX: The Other Side of the Coin](https://medium.com/@housecor/react-s-jsx-the-other-side-of-the-coin-2ace7ab62b98#.b5vs0bs70)",
        "[MDN - import](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import)",
        "[MDN - export](https://developer.mozilla.org/en/docs/web/javascript/reference/statements/export)",
        "[http://www.2ality.com/2014/09/es6-modules-final.html](http://www.2ality.com/2014/09/es6-modules-final.html)",
        "[jQuery Deferred](https://api.jquery.com/category/deferred-object/)",
        "[MDN](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Promise)",
        "[http://jquery.com/](http://jquery.com/)",
        "[http://api.jquery.com/](http://api.jquery.com/)",
        "[http://api.jquery.com/on/](http://api.jquery.com/on/)",
        "[jQuery Form Plugin](http://malsup.com/jquery/form/)",
        "[jQuery Validation Plugin](https://jqueryvalidation.org/)",
        "[es5-shim](https://github.com/es-shims/es5-shim)",
        "[http://stackoverflow.com/questions/32148218/why-does-object-assign-require-a-polyfill-when-babel-loader-is-being-used](http://stackoverflow.com/questions/32148218/why-does-object-assign-require-a-polyfill-when-babel-loader-is-being-used)",
        "[HTML5 PLEASE](http://html5please.com/)",
        "[Lodash](https://lodash.com/)",
        "[Lazy.js](http://danieltao.com/lazy.js/)",
        "[Immutable](https://facebook.github.io/immutable-js/)",
        "[http://kangax.github.io/compat-table/es6/](http://kangax.github.io/compat-table/es6/)",
        "[http://kangax.github.io/compat-table/es2016plus/](http://kangax.github.io/compat-table/es2016plus/)",
        "[http://ilikekillnerds.com/2015/01/transpiling-wars-6to5-vs-traceur/](http://ilikekillnerds.com/2015/01/transpiling-wars-6to5-vs-traceur/)",
        "[TypeScript](https://www.typescriptlang.org/)",
        "[playground](https://www.typescriptlang.org/play/index.html)",
        "[Chrome DevTools](https://developers.google.com/web/tools/chrome-devtools/)",
        "[Chrome Canary](https://www.google.com/intl/en/chrome/browser/canary.html)",
        "[Firebug](http://getfirebug.com/)",
        "[Firefox Developer Tools](https://developer.mozilla.org/en-US/docs/Tools)",
        "[Firefox Developer Edition](https://www.mozilla.org/en-GB/firefox/developer/)",
        "[JSFiddle](https://jsfiddle.net/)",
        "[WebStorm](https://www.jetbrains.com/webstorm/)",
        "[Atom](https://atom.io/)",
        "[Visual Studio Code](https://code.visualstudio.com/c?utm_expid=101350005-35.Eg8306GUR6SersZwpBjURQ.2&utm_referrer=https%3A%2F%2Fwww.google.co.uk%2F)",
        "[JSLint](http://www.jslint.com/)",
        "[JSHint](http://jshint.com/)",
        "[ESLint](http://eslint.org/)",
        "[Mocha](https://mochajs.org/)",
        "[QUnit](https://qunitjs.com/)",
        "[Jest](https://facebook.github.io/jest/)",
        "[Headless Browsers](https://en.wikipedia.org/wiki/Headless_browser)",
        "[PhantomJS](http://phantomjs.org/)",
        "[Istanbul](https://github.com/gotwarlost/istanbul)",
        "[Jasmine](https://jasmine.github.io/)",
        "[jasmin-jquery](https://github.com/velesin/jasmine-jquery)",
        "[JSDoc](http://usejsdoc.org/)",
        "[@function](http://usejsdoc.org/tags-function.html)",
        "[@param](http://usejsdoc.org/tags-param.html)",
        "[Raphaël](http://dmitrybaranovskiy.github.io/raphael/)",
        "[three.js](https://threejs.org/)",
        "[Velocity.js](Velocity.js)",
        "[GreenSock](https://greensock.com/get-started-js)",
        "[Processing.js](http://processingjs.org/exhibition/)",
        "[AngularJS](https://angularjs.org/)",
        "[React](https://facebook.github.io/react/)",
        "[Redux](http://redux.js.org/docs/basics/UsageWithReact.html)",
        "[Aurelia](http://aurelia.io/)",
        "[KnockoutJS](http://knockoutjs.com/)",
        "[Vue](https://vuejs.org/)",
        "[jQuery UI](https://jqueryui.com/)",
        "[Node.js](https://nodejs.org/en/)",
        "[npm](https://www.npmjs.com/)",
        "[most starred npm packages](https://www.npmjs.com/browse/star)",
        "[W3Schools JavaScript Tutorial](http://www.w3schools.com/js)",
        "[Google JavaScript Style Guide](https://google.github.io/styleguide/javascriptguide.xml)",
        "[JavaScript 101](http://hsablonniere.github.io/markleft/prezas/javascript-101.html)",
        "[Code Conventions for the JavaScript Programming Language](http://javascript.crockford.com/code.html)",
        "[7 Essential JavaScript Functions](https://davidwalsh.name/essential-javascript-functions)",
        "[Seven JS Concepts You Must Understand Before Your Next Job Interview](https://gist.github.com/ericelliott/263f24b5ad987e2f09d2)",
        "[Stop Nesting Functions! (But Not All of Them)](http://code.tutsplus.com/tutorials/stop-nesting-functions-but-not-all-of-them--net-22315)",
        "[JavaScript Common Mistakes](http://www.w3schools.com/js/js_mistakes.asp)",
        "[16 Common JavaScript Gotchas](http://www.standardista.com/javascript/15-common-javascript-gotchas/)",
        "[JavaScript: The Good Parts Paperback by Douglas Crockford](https://www.amazon.co.uk/JavaScript-Good-Parts-Douglas-Crockford/dp/0596517742)",
	};
	
	var newLinks = originalLinks.Select(s => GenerateAnchorLinkWithTargetBlank(s));
	
	//originalLinks.Dump();
	newLinks.Dump();
}

private string GenerateAnchorLinkWithTargetBlank(string markdownLink)
{
	var match = Regex.Match(markdownLink, @"\[(?<text>.+)\]\((?<url>.+)\)");
	if (match.Success)
	{
		var newMarkup = String.Format("<a href=\"{0}\" target=\"_blank\" dummy=\"_\">{1}</a>",
									  match.Groups["url"].Captures[0].Value,
									  match.Groups["text"].Captures[0].Value);
		return newMarkup;
	}
	return "CANNOT CONVERT";
}